import { SprintQuestion } from './types';

export const sprintQuestions: SprintQuestion[] = [
  {
    id: 'q1_goal',
    question: 'What brings you to Purpose & Profit Builders today?',
    type: 'single',
    required: true,
    options: [
      { id: 'start-business', text: 'Start or grow a faith-aligned business' },
      { id: 'consistent-income', text: 'Build consistent income ($0\u2013$10K/mo)' },
      { id: 'ai-systems', text: 'Learn to use AI to simplify my business' },
      { id: 'exploring', text: 'Just exploring / learning' },
    ],
  },
  {
    id: 'q2_income',
    question: "What's your current monthly income from your business or side hustle?",
    type: 'single',
    required: true,
    options: [
      { id: 'zero', text: "$0 \u2014 Haven't started yet" },
      { id: 'under-1k', text: 'Under $1,000' },
      { id: '1k-3k', text: '$1,000 \u2013 $3,000' },
      { id: '3k-5k', text: '$3,000 \u2013 $5,000' },
      { id: '5k-10k', text: '$5,000 \u2013 $10,000' },
      { id: '10k-plus', text: '$10,000+' },
    ],
  },
  {
    id: 'q3_offer',
    question: 'Do you currently have a product, service, or offer you sell?',
    type: 'single',
    required: true,
    options: [
      { id: 'yes-selling', text: "Yes, and I'm actively selling it" },
      { id: 'yes-not-selling', text: "Yes, but I'm not consistently selling" },
      { id: 'idea-only', text: "I have an idea but haven't launched" },
      { id: 'no-idea', text: "No, I'm not sure what to sell" },
    ],
  },
  {
    id: 'q4_ai_usage',
    question: 'How are you currently using AI tools in your business?',
    type: 'single',
    required: true,
    options: [
      { id: 'daily', text: "Daily \u2014 it's part of my workflow" },
      { id: 'sometimes', text: 'Sometimes \u2014 I use ChatGPT here and there' },
      { id: 'tried', text: "I've tried it but don't know how to apply it" },
      { id: 'never', text: "I haven't used AI at all" },
    ],
  },
  {
    id: 'q5_systems',
    question: 'Do you have repeatable systems for getting clients or making sales?',
    type: 'single',
    required: true,
    options: [
      { id: 'yes', text: 'Yes \u2014 I have a system that works' },
      { id: 'somewhat', text: "Somewhat \u2014 but it's inconsistent" },
      { id: 'no', text: "No \u2014 I'm figuring it out as I go" },
    ],
  },
  {
    id: 'q6_faith_alignment',
    question: 'How aligned does your current work feel with your God-given purpose?',
    type: 'single',
    required: true,
    options: [
      { id: 'fully-aligned', text: 'Fully aligned \u2014 I feel called to this' },
      { id: 'mostly-aligned', text: "Mostly aligned \u2014 but something's off" },
      { id: 'not-aligned', text: "Not aligned \u2014 I'm working just for money" },
      { id: 'unsure', text: "Unsure \u2014 I'm still figuring out my purpose" },
    ],
  },
  {
    id: 'q7_time_spent',
    question: 'How many hours per week do you dedicate to building your business?',
    type: 'single',
    required: true,
    options: [
      { id: 'under-5', text: 'Under 5 hours' },
      { id: '5-10', text: '5\u201310 hours' },
      { id: '10-20', text: '10\u201320 hours' },
      { id: '20-plus', text: '20+ hours (full-time)' },
    ],
  },
  {
    id: 'q8_description',
    question: 'Briefly describe what you do or what kind of business you want to build.',
    type: 'text',
    required: true,
  },
  {
    id: 'q9_challenge',
    question: "What's your biggest challenge right now?",
    type: 'single',
    required: true,
    options: [
      { id: 'no-clients', text: 'Getting clients consistently' },
      { id: 'no-offer', text: 'Creating an offer people will pay for' },
      { id: 'no-systems', text: "Building systems so I'm not doing everything manually" },
      { id: 'no-clarity', text: 'Clarity on what to focus on' },
      { id: 'overwhelmed', text: 'Feeling overwhelmed and stuck' },
    ],
  },
  {
    id: 'q10_fix_one_thing',
    question: 'If you could fix one thing in your business right now, what would it be?',
    type: 'single',
    required: true,
    options: [
      { id: 'income', text: 'Consistent monthly income' },
      { id: 'systems', text: 'Automated systems that work without me' },
      { id: 'clarity', text: 'A clear step-by-step plan' },
      { id: 'confidence', text: "Confidence that I'm on the right path" },
    ],
  },
];
