import { CreditQuizQuestion } from './types';

export const creditGPSQuestions: CreditQuizQuestion[] = [
  {
    id: 'q1_goal',
    question: 'What brings you to The Credit Hub today?',
    type: 'single',
    required: true,
    options: [
      { id: 'fix-credit', text: 'Fix my personal credit' },
      { id: 'get-funding', text: 'Get approved for business funding' },
      { id: 'both', text: 'Both — fix credit AND get funded' },
      { id: 'exploring', text: 'Just exploring / learning' },
    ],
  },
  {
    id: 'q2_fico',
    question: "What's your current FICO score range?",
    type: 'single',
    required: true,
    options: [
      { id: 'under-600', text: 'Under 600' },
      { id: '600-680', text: '600 – 680' },
      { id: '680-700', text: '680 – 700' },
      { id: '700-750', text: '700 – 750' },
      { id: '750-plus', text: '750+' },
      { id: 'not-sure', text: "Not sure" },
    ],
  },
  {
    id: 'q3_negatives',
    question: 'Do you have any negative items on your credit report? (Select all that apply)',
    type: 'multi-select',
    required: true,
    options: [
      { id: 'collections', text: 'Collections' },
      { id: 'late-payments', text: 'Late payments' },
      { id: 'repo', text: 'Repossession' },
      { id: 'bankruptcy', text: 'Bankruptcy' },
      { id: 'multiple', text: 'Multiple negative items' },
      { id: 'getting-removed', text: 'Currently getting items removed' },
      { id: 'clean', text: 'Clean — no negative items' },
    ],
  },
  {
    id: 'q4_utilization',
    question: "What's your current credit utilization?",
    type: 'single',
    required: true,
    options: [
      { id: 'debt-free', text: 'Debt free' },
      { id: 'under-15', text: 'Under 15%' },
      { id: '15-30', text: '15% – 30%' },
      { id: '30-50', text: '30% – 50%' },
      { id: '50-plus', text: '50%+' },
      { id: 'can-reduce', text: 'Can reduce under 20%' },
    ],
  },
  {
    id: 'q5_two_cards',
    question: 'Do you have at least two primary credit cards with $2,500+ limits?',
    type: 'single',
    required: true,
    options: [
      { id: 'yes', text: 'Yes' },
      { id: 'no', text: 'No' },
    ],
  },
  {
    id: 'q6_in_business',
    question: 'Are you currently in business?',
    type: 'single',
    required: true,
    options: [
      { id: 'yes', text: 'Yes' },
      { id: 'no', text: 'No (planning to start)' },
    ],
  },
  {
    id: 'q7_revenue',
    question: 'What is your monthly business revenue?',
    type: 'single',
    required: true,
    options: [
      { id: 'just-starting', text: 'Just starting out' },
      { id: 'under-10k', text: 'Under $10K' },
      { id: '10k-25k', text: '$10K – $25K' },
      { id: '25k-50k', text: '$25K – $50K' },
      { id: '50k-plus', text: '$50K+' },
    ],
  },
  {
    id: 'q8_occupation',
    question: 'Briefly describe what you do.',
    type: 'text',
    required: true,
  },
  {
    id: 'q9_challenge',
    question: "What's your biggest challenge right now?",
    type: 'single',
    required: true,
    options: [
      { id: 'getting-approved', text: 'Getting approved for funding' },
      { id: 'cleaning-credit', text: 'Cleaning up my credit' },
      { id: 'knowing-next-steps', text: "Knowing what steps to take next" },
      { id: 'feeling-stuck', text: 'Feeling stuck / overwhelmed' },
      { id: 'staying-consistent', text: 'Staying consistent with the process' },
    ],
  },
  {
    id: 'q10_fix_one_thing',
    question: 'If you could fix one thing instantly, what would it be?',
    type: 'single',
    required: true,
    options: [
      { id: 'credit-profile', text: 'My credit profile' },
      { id: 'funding-access', text: 'Access to funding' },
      { id: 'clear-roadmap', text: 'A clear roadmap' },
      { id: 'confidence', text: 'Confidence in the process' },
    ],
  },
];
